@startuml HomeScreenVM Sequence

skinparam sequence{
    ParticipantBackgroundColor #A7BEAE
    LifeLineBackgroundColor #E7E8D1
    LifeLineBorderColor #2C5F2D
    ActorBackgroundColor #FC766AFF
    ActorBorderColor #FC766AFF
    ArrowColor #B85042
    ArrowFontColor #234E70

}
skinparam SequenceMessageAlignment center


title Change color
autonumber
hide footbox
Caller -> HomeScreenVM: Invokes colorChange()
activate Caller
activate HomeScreenVM
HomeScreenVM -> HomeScreenVM: Changes the scaffold \n color
HomeScreenVM --> Caller: Return the changed scaffold color
HomeScreenVM -> HomeScreenVM: Changes the button \n color
HomeScreenVM --> Caller: Return the changed button color
deactivate HomeScreenVM
deactivate Caller

@enduml

