@startuml HomeScreenVMVM Sequence

skinparam sequence{
    ParticipantBackgroundColor #A7BEAE
    LifeLineBackgroundColor #E7E8D1
    LifeLineBorderColor #2C5F2D
    ActorBackgroundColor #FC766AFF
    ActorBorderColor #FC766AFF
    ArrowColor #B85042
    ArrowFontColor #234E70
}

title Change color
autonumber
hide footbox
Caller --> HomeScreenVM: Invokes colorChange()
activate Caller 
activate HomeScreenVM
HomeScreenVM --> HomeScreenVM: Changes the scaffold \n and button color
HomeScreenVM --> Caller: Return the \n changed color
deactivate HomeScreenVM
deactivate Caller 

@enduml 

